---
- name: collect all the pools
  command: rados --cluster {{ cluster }} lspools
  register: ceph_pools
  when: "{{ ceph_version | version_compare('0.94.0', '>=') }}"

- name: secure the cluster
  command: ceph --cluster {{ cluster }} osd pool set {{ item[0] }} {{ item[1] }} true
  with_nested:
    - "{{ ceph_pools.stdout_lines|default([]) }}"
    - secure_cluster_flags
  when: ceph_release_num.{{ ceph_release }} >= ceph_release_num.hammer
